    version: '2'
    services:
      web:
        build: .
        ports:
         - "49160:8080"
        volumes:
         - .:/usr/src/app
        depends_on:
         - mongo
      mongo:
        image: mongo